[28 Sep, 2025 at 21:57:31] Error in swo-reader-tcp.py: Could not connect to GDB_SWO_PORT.
